# Generated by Django 4.2.8 on 2023-12-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='careerlog',
            name='categories',
            field=models.ManyToManyField(to='myapp.category'),
        ),
        migrations.AddField(
            model_name='careerlog',
            name='languages',
            field=models.ManyToManyField(to='myapp.language'),
        ),
        migrations.AddField(
            model_name='careerlog',
            name='technologies',
            field=models.ManyToManyField(to='myapp.technology'),
        ),
    ]
